const PHOTOS=['1Qqbqb0PGfz9gXSbXrmHnBOL_2GUFtIKx','1IwoxYmDaZq3MWLbacjH71PiWJxHBXpWw','1cvf9JIn3hoXHsiuMd3A1vsTTcsIqZ25H','1UbhNEzRGLqp4CasUmnNzG3fwSwkospZG','12N8pL7cZnejvtwqtu8EShZMvxTPoCb7u','1Hz95D0BwdTJPyxVZKsPUAf8ZzeygdoXI','1XjNUbkGB8ucu3MbrQBFkGK3JV6RkTAvg','1QFjNaFawujj1Xk10ILIzXFtKXKqAujb9','1StFGgrMDc1c7WagNr92RUuPp8_Fum6A_','1WKTOVe-I4bBniRh2jUnTgeboqTfOzPBH','1WIXbYdUWS8bDqS6KgMiX1_zquzTmfFAR','1nFISBpQdKyeCNAwksPhs6SM9gLKAPMgW','10nRHrhJ9aHobwDu5WojDYEhEOtSalwsp','1dE6HOhTkCdBJjWOL22LlESYNEWC7u61K','1OsPbp8hitRQffIMCxNyWnEgWu7ZwPL1J','1eNWSpt7_5_9SyqQOuUozA2--2z991TeB','1dM4Ec6drx7w3wlf8O8jGHv_lPzdqsili','1rvCS0nPOHA2JRtZtdVyO3k4lmdI161sQ','1JYrneYAQb2ZhujmrBU7Iq-l1rcf4Kb76','1EOV7eBw-h0xJ2jfQwVdyFa8IE2R1Rt9l','13x0U7Z2gFF8bTzq1Hj_36uIRBdqUh_iw','1q0ZvW6duFH4woP4RLW7qBCtCK6-TkyGh','1aRnDAie12AzVU4t7dLEmspKNANOtAs5S','1BKWYwGhpKvz3i5EcinwQlrtmEVEX7eMQ','1GNRFtjVepBUaJii-Tb8ascTnB91P1knp','1GeizL3J9gTutQfLtDRPMYRtRrTKw01V9','1TkHqnZ-z-3CWZNlTLqZsGxh9SXHRDqWs','1CPJVeM4t-L0HIbnb1D5QHzZyZnP38H1d','1iseb396Meo1SoB6TFLXCXeOdBNKd6aLG','1oQ3QZg-o07f1NDdpFh8paEiW0PuqA4a4','1yjvKlRcwj9CSn9GPbBp5jxA1PX6C9Xib','1BOcsqmWMSz-e8UwGWjIg7bx7xfcK7X9R','1C6cWaYYjowBR1gk0X5Au5CJzEALtYuDL','1BG8cPJkGOe_LmXzE2z7o5ZsuZAobkOI8','1HSIjwYiRFqT1GlH7nNUCoeckg5a2C8wO','1Isy24KiNcCHXgOfmctc8F8wT6PMv9pok','1jbNEEyQNZqZj16_P9SGPj7pT3cluwYiW','12JcWc4BENHa0hcqQ93UCQejfhR88Fk7m','1trynYggiQgzutyk7hKU8fNfXqUi8anAd','1gmis4K9As3KtzNIcdCbABkwXdnWvazG_','1kQpf3Qi-terznyWNDkvj_HMxitswVem9','1vkeBl2YiN4VOIiLhRwzbUBxTcEiyf0je','1gWxJSd8kpyKId9VHLg_9G3-J7wJs9Ts8','1SwK2Aat0amtgXIYGGX-UiM1LTSa0TCmJ','1upFgVSgeNOZKPOxR2643oU4o-i6OKnHG','1qMyUXd-DRh6P3u3At1xMYSfmK1JRaa5D','1ku6D2t1KY2B1WBobfXar8VpTzGEOq0hR','1wKbrNjo8FCmkPbiIwVRDz1RCQb4p_K8s','1-rViuU9DWNFOqFNjt0RCuVQZHwWkMkN-','1cukGhZ6I3iu58PWdKfKSbJpYj3l8fneB','1FXXLhS5U1pzgz2E_4dwDVr4eiBH1ItK9','1f-Zr4vIBcP-O4PbtgkomTvZDHhTvUKBf','1rR_XkNpFCI-1DV0GM7xRpOsIJCqlMo8x','1usMZVeD0aobDcbDK0a2LzP9Ue-0Q3tCZ','1by5MAHzcwk62n9pmpQXiPpW1ESS1YOAM'];
const photos=document.getElementById('photos'),galaxy=document.getElementById('galaxy'),space=document.getElementById('space');
let zoom=1,auto=true,dragging=false,lastX=0,lastY=0;
const cards=[];
PHOTOS.forEach((id,i)=>{const el=document.createElement('button');el.className='photo';el.type='button';const img=document.createElement('img');img.src=`https://lh3.googleusercontent.com/d/${id}`;img.loading='lazy';img.draggable=false;img.onerror=()=>{if(!img.dataset.f){img.dataset.f=1;img.src=`https://drive.google.com/thumbnail?id=${id}&sz=w1600`}};const label=document.createElement('small');label.textContent=`MEMORY ${String(i+1).padStart(2,'0')}`;el.append(img,label);el.onclick=()=>openViewer(id,i);photos.append(el);
const seed=i*137.508;const angle=(seed*Math.PI/180);const radius=250+(i%11)*78;cards.push({el,baseX:Math.cos(angle)*radius,baseY:Math.sin(angle)*radius*.66,baseZ:(i%7)*38-80,floatX:10+(i%5)*5,floatY:12+(i%6)*4,floatZ:18+(i%4)*5,phase:i*.91,spinPhase:i*1.37,spinSpeed:.18+(i%5)*.025,drift:.7+(i%4)*.12,size:.88+(i%4)*.045});});
function render(t){const w=window.innerWidth,h=window.innerHeight;const sx=Math.max(1,w/1050),sy=Math.max(1,h/720);const scale=zoom*(w<700?.68:1);cards.forEach(c=>{const x=c.baseX*sx+Math.sin(t*c.drift+c.phase)*c.floatX;const y=c.baseY*sy+Math.cos(t*c.drift*.82+c.phase)*c.floatY;const z=c.baseZ+Math.sin(t*.65+c.phase)*c.floatZ;const yaw=Math.sin(t*c.spinSpeed+c.spinPhase)*4;const roll=Math.sin(t*.43+c.phase)*1.2;const s=c.size*(.92+Math.max(0,z+120)/260*.08);c.el.style.transform=`translate3d(${x}px,${y}px,${z}px) rotateY(${yaw}deg) rotateZ(${roll}deg) scale(${s})`;c.el.style.opacity=.78+Math.max(0,z+120)/260*.22;c.el.style.zIndex=Math.round(z+500)});galaxy.style.transform=`translate(-50%,-50%) scale(${scale})`}
let last=performance.now();function loop(now){const dt=Math.min(40,now-last);last=now;if(auto&&!dragging){}render(now*.001);requestAnimationFrame(loop)}requestAnimationFrame(loop);
space.addEventListener('pointerdown',e=>{dragging=true;space.classList.add('dragging');lastX=e.clientX;lastY=e.clientY;space.setPointerCapture(e.pointerId)});space.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;cards.forEach(c=>{c.baseX+=dx*.12;c.baseY+=dy*.12});lastX=e.clientX;lastY=e.clientY});space.addEventListener('pointerup',()=>dragging=false);space.addEventListener('pointercancel',()=>dragging=false);space.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.72,Math.min(1.25,zoom-e.deltaY*.00055))},{passive:false});
document.getElementById('auto').onclick=()=>{auto=!auto;document.getElementById('auto').innerHTML=`AUTO FLOAT <b>${auto?'ON':'OFF'}</b>`};
const viewer=document.getElementById('viewer'),viewerImg=document.getElementById('viewerImg'),viewerText=document.getElementById('viewerText');function openViewer(id,i){viewerImg.src=`https://lh3.googleusercontent.com/d/${id}`;viewerImg.onerror=()=>viewerImg.src=`https://drive.google.com/thumbnail?id=${id}&sz=w2000`;viewerText.textContent=`BAGAN · MEMORY ${String(i+1).padStart(2,'0')} · ${PHOTOS.length} FRAMES`;viewer.classList.add('open');viewer.setAttribute('aria-hidden','false');auto=false}function closeViewer(){viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true')}document.getElementById('close').onclick=closeViewer;viewer.onclick=e=>{if(e.target===viewer)closeViewer()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeViewer()});